# Analysis of The Movie Data Base Data
## The following analysis explores the various attributes of successful movies

### It should be noted that a movie's success can be defined a few different ways based on this data. Successfull movies and how one success may relate to another (e.g voter score vs. total revenue) will be explored by answering the following questions

### -What were the most expensive movies each and their adjusted budgets for all available years in the data, and how did they compare to the most profitable and highly voted movies for that year?

### -Which genres had the highest adjusted revenue year to year? Which genres were the most expensive to produce? How did the adjusted budgets of the most profitable movies compare to the most expensive genres year to year?

###  -What movies had the largest adjusted revenues every year? How did they compare when analysing and comparing their various attributes (e.g genre, voter score, runtime, budget, voting score)?

### -How does runtime effect adjusted revenues?

# Data Cleaning

In [1]:
#Reading the csv file into a pandas dataframe
import pandas as pd
import numpy as np

np.set_printoptions(suppress=True)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

#I created two data frame objects one that contains the orginal data set, and another that contain and edit or cleaning done
tmdb_data = pd.read_csv('tmdb-movies.csv')
tmdb_data_edited = pd.read_csv('tmdb-movies.csv')

tmdb_data.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.986,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.500,2015,137999939.300,1392445893.000
1,76341,tt1392190,28.420,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.100,2015,137999939.300,348161292.500
2,262500,tt2908446,13.113,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.300,2015,101199955.500,271619025.400
3,140607,tt2488496,11.173,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.500,2015,183999919.000,1902723130.000
4,168259,tt2820852,9.335,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.300,2015,174799923.100,1385748801.000

In [2]:
tmdb_data

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.986,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.500,2015,137999939.300,1392445893.000
1,76341,tt1392190,28.420,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.100,2015,137999939.300,348161292.500
2,262500,tt2908446,13.113,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.300,2015,101199955.500,271619025.400
3,140607,tt2488496,11.173,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.500,2015,183999919.000,1902723130.000
4,168259,tt2820852,9.335,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.300,2015,174799923.100,1385748801.000
5,281957,tt1663202,9.111,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃƒÂ¡lez IÃƒÂ±ÃƒÂ¡rritu,"(n. One who has returned, as if from the dead.)",...,"In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,12/25/2015,3929,7.200,2015,124199945.400,490314247.000
6,87101,tt1340138,8.654,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,...,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,6/23/2015,2598,5.800,2015,142599937.300,405355075.700
7,286217,tt3659388,7.667,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,9/30/2015,4572,7.600,2015,99359956.280,547749654.300
8,211672,tt2293640,7.404,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",...,"Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,6/17/2015,2893,6.500,2015,68079970.040,1064192017.000
9,150540,tt2096673,6.327,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,3935,8.000,2015,160999929.200,785411574.700
10,206647,tt2379713,6.200,245000000,880674609,Spectre,Daniel Craig|Christoph Waltz|LÃƒÂ©a Seydoux|Ralp...,http://www.sonypictures.com/movies/spectre/,Sam Mendes,A Plan No One Escapes,...,A cryptic message from BondÃ¢â‚¬â„¢s past sends him...,148,Action|Adventure|Crime,Columbia Pictures|Danjaq|B24,10/26/2015,3254,6.200,2015,225399900.800,810220283.800
11,76757,tt1617661,6.189,176000003,183987723,Jupiter Ascending,Mila Kunis|Channing Tatum|Sean Bean|Eddie Redm...,http://www.jupiterascending.com,Lana Wachowski|Lilly Wachowski,Expand your universe.,...,In a universe where human genetic material is ...,124,Science Fiction|Fantasy|Action|Adventure,Village Roadshow Pictures|Dune Entertainment|A...,2/4/2015,1937,5.200,2015,161919931.500,169268630.700
12,264660,tt0470752,6.119,15000000,36869414,Ex Machina,Domhnall Gleeson|Alicia Vikander|Oscar Isaac|S...,http://exmachina-movie.com/,Alex Garland,There is nothing more human than the will to s...,...,"Caleb, a 26 year old coder at the world's larg...",108,Drama|Science Fiction,DNA Films|Universal Pictures International (UP...,1/21/2015,2854,7.600,2015,13799993.930,33919845.960
13,257344,tt2120120,5.985,88000000,243637091,Pixels,Adam Sandler|Michelle Monaghan|Peter Dinklage|...,http://www.pixels-movie.com/,Chris Columbus,Game On.,...,Video game experts are recruited by the milita...,105,Action|Comedy|Science Fiction,Columbia Pictures|Happy Madison Productions,7/16/2015,1575,5.800,2015,80959964.380,224146025.100
14,99861,tt2395427,5.945,280000000,1405035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,http://marvel.com/movies/movie/193/avengers_ag...,Joss Whedon,A New Age Has Come.,...,When Tony Stark tries to jumpstart a dormant p...,141,Action|Adventure|Science Fiction,Marvel Studios|Prime Focus|Revolution Sun Studios,4/22/2015,4304,7.400,2015,257599886.700,1292632337.000
15,273248,tt3460252,5.898,44000000,155760117,The Hateful Eight,Samuel L. Jackson|Kurt Russell|Jennifer Jason ...,http://thehatefuleight.com/,Quentin Tarantino,No one comes up here without a damn good reason.,...,Bounty hunters seek shelter from a raging bliz...,167,Crime|Drama|Mystery|Western,Double Feature Films|The Weinstein Company|Fil...,12/25/2015,2389,7.400,2015,40479982.190,143299244.600
16,260346,tt2446042,5.750,48000000,325771424,Taken 3,Liam Neeson|Forest Whitaker|Maggie Grace|Famke...,http://www.taken3movie.com/,Olivier Megaton,It Ends Here,...,Ex-government operative Bryan Mills finds his ...,109,Crime|Action|Thriller,Twentieth Century Fox Film Corporation|M6 Film...,1/1/2015,1578,6.100,2015,44159980.570,299709578.200
17,102899,tt0478970,5.573,130000000,518602163,Ant-Man,Paul Rudd|Michael Douglas|Evangeline Lilly|Cor...,http://marvel.com/movies/movie/180/ant-man,Peyton Reed,Heroes Don't Get Any Bigger,...,Armed with the astonishing ability to shrink i...,115,Science Fiction|Action|Adventure,Marvel Studios,7/14/2015,3779,7.000,2015,119599947.400,477113780.000
18,150689,tt1661199,5.557,95000000,542351353,Cinderella,Lily James|Cate Blanchett|Richard Madden|Helen...,NaN,Kenneth Branagh,Midnight is just the beginning.,...,"When her father unexpectedly passes away, youn...",112,Romance|Fantasy|Family|Drama,Walt Disney Pictures|Genre Films|Beagle Pug Fi...,3/12/2015,1495,6.800,2015,87399961.540,498963025.200
19,131634,tt1951266,5.477,160000000,650523427,The Hunger Games: Mockingjay - Part 2,Jennifer Lawrence|Josh Hutcherson|Liam Hemswor...,http://www.thehungergames.movie/,Francis Lawrence,The fire will burn forever.,...,"With the nation of Panem in a full scale war, ...",136,War|Adventure|Science Fiction,Studio Babelsberg|StudioCanal|Lionsgate|Walt D...,11/18/2015,2380,6.500,2015,147199935.200,598481289.500
20,158852,tt1964418,5.462,190000000,209035668,Tomorrowland,Britt Robertson|George Clooney|Raffey Cassidy|...,http://movies.disney.com/tomorrowland,Brad Bird,Imagine a world where nothing is impossible.,...,"Bound by a shared destiny, a bright, optimisti...",130,Action|Family|Science Fiction|Adventure|Mystery,Walt Disney Pictures|Babieka|A113,5/19/2015,1899,6.200,2015,174799923.100,192312729.900
21,307081,tt1798684,5.337,30000000,91709827,Southpaw,Jake Gyllenhaal|Rachel McAdams|Forest Whitaker...,NaN,Antoine Fuqua,Believe in Hope.,...,"Billy ""The Great"" Hope, the reigning junior mi...",123,Action|Drama,Escape Artists|Riche-Ludwig Productions,6/15/2015,1386,7.300,2015,27599987.860,84373003.720
22,254128,tt2126355,4.908,110000000,470490832,San Andreas,Dwayne Johnson|Alexandra Daddario|Carla Gugino...,http://www.sanandreasmovie.com/,Brad Peyton,"A rescue pilot survived an earthquake, this is...",...,In the aftermath of a massive earthquake in Ca...,114,Action|Drama|Thriller,New Line Cinema|Village Roadshow Pictures|Warn...,5/27/2015,2060,6.100,2015,101199955.500,432851375.000
23,216015,tt2322441,4.710,40000000,569651467,Fifty Shades of Grey,Dakota Johnson|Jamie Dornan|Jennifer Ehle|Eloi...,https://www.facebook.com/fiftyshadesofgreymovie,Sam Taylor-Johnson,Are you curious?,...,When college senior Anastasia Steele steps in ...,125,Drama|Romance,Focus Features|Trigger Street Productions|Mich...,2/11/2015,1865,5.300,2015,36799983.810,524079119.000
24,318846,tt1596363,4.648,28000000,133346506,The Big Short,Christian Bale|Steve Carell|Ryan Gosling|Brad ...,http://www.thebigshortmovie.com/,Adam McKay,This is a true story.,...,The men who made millions from a global econom...,130,Comedy|Drama,Paramount Pictures|Plan B Entertainment|Regenc...,12/11/2015,1545,7.300,2015,25759988.670,122678731.500
25,177677,tt2381249,4.567,150000000,682330139,Mission: Impossible - Rogue Nation,Tom Cruise|Jeremy Renner|Simon Pegg|Rebecca Fe...,http://www.missionimpossible.com,Christopher McQuarrie,Desperate Times. Desperate Measures.,...,Ethan and team take on their most impossible m...,131,Action,Paramount Pictures|Skydance Productions|China ...,7/23/2015,2349,7.100,2015,137999939.300,627743451.700
26,214756,tt2637276,4.565,68000000,215863606,Ted 2,Mark Wahlberg|Seth MacFarlane|Amanda Seyfried|...,NaN,Seth MacFarlane,"Ted is Coming, Again.",...,Newlywed couple Ted and Tami-Lynn want to have...,115,Comedy,Universal Pictures|Media Rights Capital|Fuzzy ...,6/25/2015,1666,6.300,2015,62559972.470,198594430.100
27,207703,tt2802144,4.504,81000000,403802136,Kingsman: The Secret Service,Taron Egerton|Colin Firth|Samuel L. Jackson|Mi...,http://www.kingsmanmovie.com/,Matthew Vaughn,Manners maketh man.,...,The story of a super-secret spy organization t...,130,Crime|Comedy|Action|Adventure,Twentieth Century Fox Film Corporation|Marv Fi...,1/24/2015,3833,7.600,2015,74519967.210,371497801.700
28,314365,tt1895587,4.062,20000000,88346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,http://www.spotlightthefilm.com,Tom McCarthy,Break the story. Break the silence.,...,The true story of how The Boston Globe uncover...,128,Drama|Thriller|History,Participant Media|Open Road Films|Anonymous Co...,11/6/2015,1559,7.800,2015,18399991.900,81278719.400
29,294254,tt4046784,3.969,61000000,311256926,Maze Runner: The Scorch Trials,Dylan O'Brien|Kaya Scodelario|Thomas Brodie-Sa...,http://mazerunnermovies.com,Wes Ball,The Maze Was Just the Beginning.,...,Thomas and his fellow Gladers face their great...,132,Action|Science Fiction|Thriller,Gotham Group|Temple Hill Entertainment|TSG Ent...,9/9/2015,1849,6.400,2015,56119975.310,286356245.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,38720,tt0061170,0.239,0,0,Walk Don't Run,Cary Grant|Samantha Eggar|Jim Hutton|John Stan...,NaN,Charles Walters,"Run, don't walk to see Walk, Don't Run.",...,"British industrialist Sir William Rutland - ""B...",114,Comedy|Romance,Columbia Pictures Corporation,1/1/1966,11,5.800,1966,0.000,0.000
10837,19728,tt0060177,0.292,0,0,The Blue Max,George Peppard|James Mason|Ursula Andress|Jere...,NaN,John Guillermin,There was no quiet on the Western Front!,...,"A young pilot in the German air force of 1918,...",156,War|Action|Adventure|Drama,Twentieth Century Fox Film Corporation,6/21/1966,12,5.500,1966,0.000,0.000
10838,22383,tt0060862,0.152,0,0,The Professionals,Burt Lancaster|Lee Marvin|Robert Ryan|Woody St...,NaN,Richard Brooks,"Rough, tough and ready.",...,The Professionals is a 1966 American Western f...,117,Action|Adventure|Western,Columbia Pictures,11/1/1966,21,6.000,1966,0.000,0.000
10839,13353,tt0060550,0.276,0,0,"It's the Great Pumpkin, Charlie Brown",Christopher Shea|Sally Dryer|Kathy Steinberg|A...,NaN,Bill Melendez,Every year he rises from the pumpkin patch...,...,"This classic ""Peanuts"" tale focuses on the thu...",25,Family|Animation,Warner Bros. Home Video,10/27/1966,49,7.200,1966,0.000,0.000
10840,34388,tt0060437,0.103,0,0,Funeral in Berlin,Michael Caine|Paul Hubschmid|Oskar Homolka|Eva...,NaN,Guy Hamilton,NaN,...,"Colonel Stok, a Soviet intelligence officer re...",102,Thriller,Lowndes Productions Limited,12/22/1966,13,5.700,1966,0.000,0.000
10841,42701,tt0062262,0.265,75000,0,The Shooting,Will Hutchins|Millie Perkins|Jack Nicholson|Wa...,NaN,Monte Hellman,"Suspenseful desert pursuit in the ""High Noon"" ...",...,A hired gun seeks to enact revenge on a group ...,82,Western,Proteus Films,10/23/1966,12,5.500,1966,503851.102,0.000
10842,36540,tt0061199,0.253,0,0,Winnie the Pooh and the Honey Tree,Sterling Holloway|Junius Matthews|Sebastian Ca...,NaN,Wolfgang Reitherman,NaN,...,Christopher Robin's bear attempts to raid a be...,25,Animation|Family,NaN,1/1/1966,12,7.900,1966,0.000,0.000
10843,29710,tt0060588,0.252,0,0,Khartoum,Charlton Heston|Laurence Olivier|Richard Johns...,NaN,Basil Dearden|Eliot Elisofon,"Where the Nile divides, the great Cinerama adv...",...,"English General Charles George Gordon, a devou...",134,Adventure|Drama|War|History|Action,Julian Blaustein Productions Ltd.,6/9/1966,12,5.800,1966,0.000,0.000
10844,23728,tt0059557,0.236,0,0,Our Man Flint,James Coburn|Lee J. Cobb|Gila Golan|Edward Mul...,NaN,Daniel Mann,The ORIGINAL man of mystery!,...,When scientists use eco-terrorism to impose th...,108,Adventure|Comedy|Fantasy|Science Fiction,20th Century Fox,1/16/1966,13,5.600,1966,0.000,0.000
10845,5065,tt0059014,0.231,0,0,Carry On Cowboy,Sid James|Jim Dale|Angela Douglas|Kenneth Will...,NaN,Gerald Thomas,How the west was lost!,...,Stodge City is in the grip of the Rumpo Kid an...,93,Comedy|Western,Peter Rogers Productions,3/1/1966,15,5.900,1966,0.000,0.000
10846,17102,tt0059127,0.213,0,0,Dracula: Prince of Darkness,Christopher Lee|Barbara Shelley|Andrew Keir|Fr...,NaN,Terence Fisher,"DEAD for Ten Years DRACULA, Prince of Darkness...",...,"Whilst vacationing in the Carpathian Mountain,...",90,Horror,Seven Arts Productions|Hammer Film Productions,1/9/1966,16,5.700,1966,0.000,0.000
10847,28763,tt0060548,0.035,0,0,Island of Terror,Peter Cushing|Edward Judd|Carole Gray|Eddie By...,NaN,Terence Fisher,How could they stop the devouring death...that...,...,A small island community is overrun with creep...,89,Science Fiction|Horror,Planet Film Productions|Protelco,6/20/1966,13,5.300,1966,0.000,0.000
10848,2161,tt0060397,0.207,5115000,12000000,Fantastic Voyage,Stephen Boyd|Raquel Welch|Edmond O'Brien|Donal...,NaN,Richard Fleischer,A Fantastic and Spectacular Voyage... Through ...,...,The science of miniaturization has been unlock...,100,Adventure|Science Fiction,Twentieth Century Fox Film Corporation,8/24/1966,42,6.700,1966,34362645.150,80616176.310
10849,28270,tt0060445,0.207,0,0,Gambit,Michael Caine|Shirley MacLaine|Herbert Lom|Joh...,NaN,Ronald Neame,Shirley MacLaine raises Michael Caine!,...,Harry Dean (Michael Caine) has a perfect plan ...,109,Action|Comedy|Crime,Universal Pictures,12/16/1966,14,6.100,1966,0.000,0.000
10850,26268,tt0060490,0.202,0,0,Harper,Paul Newman|Lauren Bacall|Julie Harris|Arthur ...,NaN,Jack Smight,Harper takes a case - and the payoff is murder.,...,Harper is a cynical private eye in the best tr...,121,Action|Drama|Thriller|Crime|Mystery,Warner Bros.,2/23/1966,14,6.000,1966,0.000,0.000
10851,15347,tt0060182,0.343,0,0,Born Free,Virginia McKenna|Bill Travers|Geoffrey Keen|Pe...,NaN,James Hill,From The Pages Of The Beloved Best Seller... A...,...,Born Free (1966) is an Open Road Films Ltd./Co...,95,Adventure|Drama|Action|Family|Foreign,High Road,6/22/1966,15,6.600,1966,0.000,0.000
10852,37301,tt0060165,0.227,0,0,A Big Hand for the Little Lady,Henry Fonda|Joanne Woodward|Jason Robards|Paul...,NaN,Fielder Cook,All the action you can take...all the adventur...,...,A naive traveler in Laredo gets involved in a ...,95,Western,Eden Productions Inc.,5/31/1966,11,6.000,1966,0.000,0.000
10853,15598,tt0060086,0.164,0,0,Alfie,Michael Caine|Shelley Winters|Millicent Martin...,NaN,Lewis Gilbert,Is any man an Alfie? Ask any girl!,...,The film tells the story of a young man who le...,114,Comedy|Drama|Romance,NaN,3/29/1966,26,6.200,1966,0.000,0.000
10854,31602,tt0060232,0.146,0,0,The Chase,Marlon Brando|Jane Fonda|Robert Redford|E.G. M...,NaN,Arthur Penn,The chase is on!,...,Most everyone in town thinks that Sheriff Cald...,135,Thriller|Drama|Crime,Horizon Pictures|Columbia Pictures Corporation,2/17/1966,17,6.000,1966,0.000,0.000
10855,13343,tt0059221,0.141,700000,0,The Ghost & Mr. Chicken,Don Knotts|Joan Staley|Liam Redmond|Dick Sarge...,NaN,Alan Rafkin,G-G-GUARANTEED! YOU'LL BE SCARED UNTIL YOU LAU...,...,Luther Heggs aspires to being a reporter for h...,90,Comedy|Family|Mystery|Romance,Universal Pictures,1/20/1966,14,6.100,1966,4702610.285,0.000
10856,20277,tt0061135,0.141,0,0,The Ugly Dachshund,Dean Jones|Suzanne Pleshette|Charles Ruggles|K...,NaN,Norman Tokar,A HAPPY HONEYMOON GOES TO THE DOGS!...When a G...,...,The Garrisons (Dean Jones and Suzanne Pleshett...,93,Comedy|Drama|Family,Walt Disney Pictures,2/16/1966,14,5.700,1966,0.000,0.000
10857,5921,tt0060748,0.131,0,0,Nevada Smith,Steve McQueen|Karl Malden|Brian Keith|Arthur K...,NaN,Henry Hathaway,Some called him savage- and some called him sa...,...,Nevada Smith is the young son of an Indian mot...,128,Action|Western,Paramount Pictures|Solar Productions|Embassy P...,6/10/1966,10,5.900,1966,0.000,0.000
10858,31918,tt0060921,0.318,0,0,"The Russians Are Coming, The Russians Are Coming",Carl Reiner|Eva Marie Saint|Alan Arkin|Brian K...,NaN,Norman Jewison,IT'S A PLOT! ...to make the world die laughing!!,...,"Without hostile intent, a Soviet sub runs agro...",126,Comedy|War,The Mirisch Corporation,5/25/1966,11,5.500,1966,0.000,0.000
10859,20620,tt0060955,0.089,0,0,Seconds,Rock Hudson|Salome Jens|John Randolph|Will Gee...,NaN,John Frankenheimer,NaN,...,A secret organisation offers wealthy people a ...,100,Mystery|Science Fiction|Thriller|Drama,Gibraltar Productions|Joel Productions|John Fr...,10/5/1966,22,6.600,1966,0.000,0.000
10860,5060,tt0060214,0.087,0,0,Carry On Screaming!,Kenneth Williams|Jim Dale|Harry H. Corbett|Joa...,NaN,Gerald Thomas,Carry On Screaming with the Hilarious CARRY ON...,...,The sinister Dr Watt has an evil scheme going....,87,Comedy,Peter Rogers Productions|Anglo-Amalgamated Fil...,5/20/1966,13,7.000,1966,0.000,0.000
10861,21,tt0060371,0.081,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,NaN,Bruce Brown,NaN,...,"The Endless Summer, by Bruce Brown, is one of ...",95,Documentary,Bruce Brown Films,6/15/1966,11,7.400,1966,0.000,0.000
10862,20379,tt0060472,0.066,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,NaN,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/1966,20,5.700,1966,0.000,0.000
10863,39768,tt0060161,0.065,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,NaN,Eldar Ryazanov,NaN,...,An insurance agent who moonlights as a carthie...,94,Mystery|Comedy,Mosfilm,1/1/1966,11,6.500,1966,0.000,0.000

In [ ]:
tmdb_data.index

In [ ]:
tmdb_data_edited.rename(columns = {'vote_average':'average_vote_score'}, inplace=True)

In [ ]:
len(tmdb_data)

In [ ]:
tmdb_data.loc[0, 'original_title']

In [ ]:
# Test of data
tmdb_data_edited['original_title'].head()

In [ ]:
# Test of data
tmdb_data_edited.loc[0,'original_title']

In [ ]:
tmdb_data_edited.columns

In [ ]:
#Locating identifying all the columns with null values
tmdb_columns_with_null = tmdb_data_edited.isnull().any()
tmdb_columns_with_null

In [ ]:
#Printing out all the row that have an imdb_id value of Nan
tmdb_data_edited[tmdb_data_edited['imdb_id'].isnull() == True]

In [ ]:
tmdb_data_edited.isnull().values

In [ ]:
tmdb_data_edited.isnull().values[1]

In [ ]:
tmdb_data_edited.isnull().values[18]

In [ ]:
type(tmdb_data_edited.isnull().values)

In [ ]:
tmdb_data_edited.isnull()

In [ ]:
tmdb_data_edited[tmdb_data_edited.isnull()]

In [ ]:
tmdb_data_edited[tmdb_data_edited.isnull().values]
#For some reason this is returning all the rows that have atleast

In [ ]:
tmdb_data_edited[tmdb_data_edited.isnull().values]

In [ ]:
# DataFrame containing unique rows with atleast on NaN occurrence
nan_value_occurrence_df = tmdb_data_edited[tmdb_data_edited.isnull().values].drop_duplicates()
nan_value_occurrence_df

In [ ]:
tmdb_data_edited['homepage'].isnull() == True

In [ ]:
# All rows that have no homepage, the purpose of this is to see if the number of columns match the amount when the original
# has been filtered out in a spreadsheet program which it did
tmdb_data_edited[tmdb_data_edited['homepage'].isnull() == True]

In [ ]:
tmdb_data_edited.values == 0

In [ ]:
#Returns a row if it has a zero value, will repeat if it it has more than on zero value
zero_value_occurrence_df = tmdb_data_edited[tmdb_data_edited.values == 0]

In [ ]:
type(zero_value_occurrence_df)

In [ ]:
# Testing on returning the index of a row at fixed position
zero_value_occurrence_df.iloc[2].name

In [ ]:
# Demonstrating how duplicates in zero_value_occurrence_df work, as you can see from the code ran in this cell, the values for 
# the first row in the data if for the movie "Mr.Holmes". After looking at each value of the row, zero occurs twice
zero_value_occurrence_df.iloc[0]

In [ ]:
# After print the first five values of zero_value_occurrence_df we see the data row for "Mr.Holmes" occurring twice at the very
# top of the dataframe
zero_value_occurrence_df.head()

In [ ]:
# Created Dataframe containing unique rows from zero_value_occurrence
tmdb_zero_values = zero_value_occurrence_df.drop_duplicates()
tmdb_zero_values

In [ ]:
len(tmdb_zero_values)

In [ ]:
len(zero_value_occurrence_df.index)

In [ ]:
(tmdb_data_edited == 0).any()

In [ ]:
# Testing to see if code is working a expected
(tmdb_data_edited == 0).iloc[548].values

In [ ]:
tmdb_zero_values.iloc[548]

In [ ]:
#This cell demonstrates that logic is working as desired with true values above in the same location as all zeros below
print(tmdb_data_edited.iloc[548])

After exploring the data and trying to figure how best to clean it up, I came to the conclusion that I would be better to keep
the data all together and create separate reference data frame which will use to account for inaccurate and misleading records
in the data. At this point in the analysis, dataframes and corresponding reference info was created to account for 
inappropriate zero and NaN values. Additional cleaning will be conducted as needed.

In regards to zero values, I concluded that it didn't make sense to have them in most instances of this data set but rathar than removing the entire rows, I will only remove them from the analysis when necessary.

In cases where there were either or both zero values for budget and revenue, there was also a zero value for adjusted budget 
and revenue which inherently makes sense. Will continue to keep an eye of cases this does not hold true

# Question 1: What were the most expensive movies each year and their adjusted budgets for all available years in the data, and how did they compare to the most profitable and highly voted movies for that year?

In [ ]:
# To start answering/analyzing the first part of this question, I'm first going to figure out about how many most expensive 
# per year there should be by finding the min and max release year. Based the data wrangling I counducted, I can see that the 
# release year column does not have any NaN or zero values I have to concern my self with

print (tmdb_data_edited == 0).any()
tmdb_columns_with_null

In [ ]:
tmdb_data_edited['release_year'].describe()

In [ ]:
release_year_array = np.unique(tmdb_data_edited['release_year'].values)
print(len(release_year_array))
np.sort(release_year_array)

Based on this information we now know that the column for 'release_year' has no NaN or zero values. Returning all the unique values demonstrates that all values are the years that range from 1960 to 2015, and we now know that we should be getting about 56 values for max budgets per year, revenues for highest revenue grossing movies per year, and voting scores for most highly voted movies per year.

In [ ]:
# All the rows where 'release_year' == 1960 test
tmdb_data_edited[tmdb_data_edited['release_year'] == 1960].head()

In [ ]:
# Group all the data by 'release_year'
movie_budgets_groupedby_release_year = tmdb_data_edited.groupby('release_year')['budget_adj']
movie_budgets_groupedby_release_year

In [ ]:
# Maxes of movie_data_by_release_year
max_budget_adj_per_year = movie_budgets_groupedby_release_year.max()

In [ ]:
type(max_budget_adj_per_year)

In [ ]:
movies_with_max_adj_budget = tmdb_data_edited.loc[tmdb_data_edited['budget_adj'].isin(max_budget_adj_per_year.values)].sort_values(by=['release_year'])
movies_with_max_adj_budget

After seeing that there are more rows than expected (one for each year since 1960) I took a quick look at movies_with_max_adj_budget to see what might be the issue. I found that for some years there were multiple movies with the highest budget. For now I'm keeping and using the data as is.

In [ ]:
tmdb_data_edited['homepage'].isnull() == True

In [ ]:
tmdb_data_edited[tmdb_data_edited['homepage'].isnull() == True]

In [ ]:
movies_with_max_adj_budget['release_year'].duplicated()

In [ ]:
movies_with_max_adj_budget[movies_with_max_adj_budget['release_year'].duplicated() == True]

In [ ]:
movies_with_max_adj_budget[['id','original_title','budget_adj','revenue_adj','release_year']]

In [ ]:
movie_revenue_groupedby_release_year = tmdb_data_edited.groupby('release_year')['revenue_adj']
movie_revenue_groupedby_release_year

In [ ]:
max_revenue_adj_per_year = movie_revenue_groupedby_release_year.max()

In [ ]:
movies_with_max_adj_revenue = tmdb_data_edited.loc[tmdb_data_edited['revenue_adj'].isin(max_revenue_adj_per_year.values)].sort_values(by=['release_year'])
movies_with_max_adj_revenue

In [ ]:
def create_df_max_by_release_year(tmdb_dataframe, column_name_string):
    column_maxes_by_release_year = tmdb_dataframe.groupby('release_year')[column_name_string].max()
    max_movies_per_year = tmdb_dataframe.loc[tmdb_dataframe[column_name_string].isin(column_maxes_by_release_year.values)].sort_values(by=['release_year'])
    return max_movies_per_year

In [ ]:
pd.Series(movies_with_max_adj_budget['revenue_adj'].values, index=movies_with_max_adj_budget['release_year'])

In [ ]:
duplicate_max_budgets = movies_with_max_adj_budget[movies_with_max_adj_budget['release_year'].duplicated() == True]
print('duplicate_max_budgets has ' + str(len(duplicate_max_budgets)) + ' items')
duplicate_max_budgets

In [ ]:
duplicate_max_budgets.iloc[1]['release_year']

In [ ]:
movies_with_max_adj_budget['release_year'].values == duplicate_max_budgets.iloc[1]['release_year']

In [ ]:
movies_with_max_adj_budget[movies_with_max_adj_budget['release_year'].values == duplicate_max_budgets.iloc[1]['release_year']]

In [ ]:
from random import randint

randint(0,len(duplicate_max_budgets))

In [ ]:
movies_with_max_adj_budget[movies_with_max_adj_budget['release_year'].values == duplicate_max_budgets.iloc[randint(0,len(duplicate_max_budgets))]['release_year']]

In [ ]:
movies_with_max_adj_budget[movies_with_max_adj_budget['release_year'].values == duplicate_max_budgets.iloc[1]['release_year']]

In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")

pd.Series(movies_with_max_adj_budget['revenue_adj'].values, index=movies_with_max_adj_budget['release_year']).plot(figsize=(20, 10),legend=True,label='x')
pd.Series(movies_with_max_adj_revenue['revenue_adj'].values, index=movies_with_max_adj_revenue['release_year']).plot(figsize=(20, 10),legend=True,label='y')

In [ ]:
plt.figure(figsize=(20,10))
plt.plot(movies_with_max_adj_budget['release_year'].values,movies_with_max_adj_budget['revenue_adj'].values, label='Largest Budget Revenues')
plt.plot(movies_with_max_adj_revenue['release_year'].values,movies_with_max_adj_revenue['revenue_adj'].values, label='Highest Grossing Movie Revenues')
plt.legend()

In [ ]:
type(movies_with_max_adj_budget)

In [ ]:
def plot_tmdb_data_by_release_year(maxes_dataframe, column_to_plot_string, label_display_string='Not Specified'):
    plt.plot(maxes_dataframe['release_year'].values, maxes_dataframe[column_to_plot_string].values, label=label_display_string)

In [ ]:
print(tmdb_data_edited['release_year'].min())
print (tmdb_data_edited['release_year'].max())

x_axis_numbering = np.linspace(tmdb_data_edited['release_year'].min(), tmdb_data_edited['release_year'].max(), 12)
x_axis_numbering

In [ ]:
plt.figure(figsize=(25,10))

plt.xticks(x_axis_numbering)

plot_tmdb_data_by_release_year(movies_with_max_adj_budget, 'revenue_adj', 'Largest Budget Revenues')
plot_tmdb_data_by_release_year(movies_with_max_adj_revenue, 'revenue_adj', 'Highest Grossing Movies Revenues')

plt.legend()

In [ ]:
movies_with_max_adj_revenue.plot(x='release_year',y='revenue_adj')
movies_with_max_adj_budget.plot(x='release_year',y='revenue_adj')

In [ ]:
# Testing on how to obtain column names
tmdb_data_edited.columns

In [ ]:
movies_with_max_average_vote_score = create_df_max_by_release_year(tmdb_data_edited, 'average_vote_score')
len(movies_with_max_average_vote_score)

In [ ]:
movies_with_max_average_vote_score

In [ ]:
max_avg_vote_score_adj_per_year = tmdb_data_edited.groupby('release_year')['average_vote_score'].max()
max_avg_vote_score_adj_per_yearmax_avg_vote_score_adj_per_year.index

In [ ]:
movies_with_max_adj_budget[['id','original_title','budget_adj','revenue_adj','release_year']].head()

In [ ]:
movies_with_max_adj_budget[movies_with_max_adj_budget['release_year'].values == randint(1960,2015)][['original_title','release_year','budget_adj']]

In [ ]:
movies_with_max_adj_revenue = tmdb_data_edited.loc[tmdb_data_edited['revenue_adj'].isin(max_revenue_adj_per_year.values)].sort_values(by=['release_year'])
movies_with_max_adj_revenue.head()

In [ ]:
max_avg_vote_score_adj_per_year.index

movies_with_max_adj_revenue = tmdb_data_edited.loc[tmdb_data_edited['revenue_adj'].isin(max_revenue_adj_per_year.values)].sort_values(by=['release_year'])
movies_with_max_adj_revenue

In [ ]:
# Highest vote score average
tmdb_data_edited[tmdb_data_edited['release_year'].values == 1960]

In [ ]:
tmdb_data_edited['release_year'].min()

In [ ]:
temp_df = tmdb_data_edited[tmdb_data_edited.groupby(['release_year'])['budget_adj'].transform(max) == tmdb_data_edited['budget_adj']]
temp_df.sort_values(by=['release_year'])

In [ ]:
temp_df_2 = tmdb_data_edited[tmdb_data_edited.groupby(['release_year'])['average_vote_score'].transform(max) == tmdb_data_edited['average_vote_score']]
temp_df_2.sort_values(by=['release_year'])

In [ ]:
def create_df_max_by_release_year(tmdb_dataframe, column_name_string):
    max_movies_per_year = tmdb_data_edited[tmdb_data_edited.groupby(['release_year'])[column_name_string].transform(max) == tmdb_data_edited[column_name_string]]
    return max_movies_per_year.sort_values(by=['release_year'])

In [ ]:
movies_with_max_adj_budget_2 = create_df_max_by_release_year(tmdb_data_edited, 'budget_adj')
len(movies_with_max_adj_budget_2)

In [ ]:
tmdb_data_edited[['original_title','director','runtime','genres','release_year']].head()

In [ ]:
genre_count = pd.Series([4,4,4,4,1], index=['Action','Adventure','Science Fiction','Thriller','Fantasy'])
genre_count

In [ ]:
genre_grid = tmdb_data_edited['genres'].str.split('|',expand=True)
genre_grid

In [ ]:
type(genre_grid[0].value_counts())

In [ ]:
A = genre_grid[0].value_counts().sort_index()
B = genre_grid[1].value_counts().sort_index()
C = genre_grid[2].value_counts().sort_index()
D = genre_grid[3].value_counts().sort_index()
E = genre_grid[4].value_counts().sort_index()

In [ ]:
print A
print B
print C
print D
print E

In [ ]:
genre_grid[4].value_counts().sort_index()

In [ ]:
sumAB = A.add(B,fill_value = 0)
sumAB

In [ ]:
sumCD = C.add(D,fill_value = 0)
sumCD

In [ ]:
(sumAB + sumCD).add(E, fill_value = 0)